### ISSUE TITLE
Idea for the language buttons

### ISSUE THREAD

**Issue by joaquinrodfer** [maikCyphlock/jsrunner-website#1]
You could try to make the color of the buttons change according to the language of the page
![image](https://github.com/maikCyphlock/jsrunner-website/assets/63302716/25c12ba8-a0e6-4426-beb5-00be8d30de6f)

**Comment by maikCyphlock** [comment]
Thanks for your tip @joaquinrodfer  and many thanks to @johansneirap to fixed it up
